version: '2'
services:
  cateno-gateway:
    container_name: cateno-container1
    privileged: true
    environment: 
     - JAVA_OPTS=-Xmx1024m -Xms256m
    build:
      context: ./
      dockerfile: cateno-gateway/Dockerfile
    image: cateno-gateway/web:latest
    ports:
      - 8080:8080
    networks:
      fiap_network1:
        ipv4_address: 172.27.0.2
    external_links: 
      - service-container:service-container
  cateno-service:
    container_name: service-container
    environment: 
     - JAVA_OPTS=-Xmx1024m -Xms256m
    build:
      context: ./
      dockerfile: service/Dockerfile
    image: service/web:latest
    depends_on:
      - cateno-gateway
    ports:
    - 9091:9091
    networks:
      fiap_network1:
        ipv4_address: 172.27.0.5
    external_links: 
      - cateno-gateway:cateno-gateway

  prometheus:
      image: prom/prometheus:v2.1.0
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      ports:
        - 9090:9090
      networks:
        fiap_network1:
          ipv4_address: 172.27.0.6
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      networks:
        fiap_network1:
          ipv4_address: 172.27.0.7
      env_file:
        - 'env.grafana'
      volumes:
        - ./gfdata:/var/lib/grafana


networks:
  fiap_network1:
    external: true