# spring:
#   cloud:
#     gateway:
#       routes:
#       - id: service_route
#         uri: http://localhost:9090/
#         predicates:
#         - Path=/service/**
#         filters:
#         - RewritePath=/service/(?<segment>/?.*), $\{segment}